models:
  available:
  - deepseek-r1:70b
  - deepseek-r1:14b
  - deepseek-r1:32b
  default: deepseek-r1:70b
ollama:
  host: http://192.168.34.46:11434
server:
  cors_origins:
  - http://localhost:5173
  host: localhost
  port: 8080
storage:
  chat_dir: ./storage/chats
  database: ./storage/database.db
