models:
  available:
  - qwen2.5:1.5b
  - deepseek-r1:1.5b
  - llama3.2:latest
  default: qwen2.5:1.5b
ollama:
  host: http://127.0.0.1:11434
server:
  cors_origins:
  - http://localhost:5173
  host: localhost
  port: 8080
storage:
  chat_dir: ./storage/chats
  database: ./storage/database.db
