models:
  available:
  - qwen2.5:1.5b
  default: qwen2.5:1.5b
ollama:
  host: http://localhost:11434
server:
  cors_origins:
  - http://localhost:5173
  host: localhost
  port: 8080
storage:
  chat_dir: ./storage/chats
  database: ./storage/database.db
