ollama:
  host: "http://localhost:11434"

storage:
  chat_dir: "./storage/chats"
  database: "./storage/database.db"

server:
  host: "localhost"
  port: 8080
  cors_origins: ["http://localhost:5173", "http://localhost:5174"]  # 开发服务器地址 